from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TrackModel(object):
    def setupUi(self, TrackModel):
        TrackModel.setObjectName("TrackModel")
        TrackModel.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        TrackModel.resize(667, 752)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TrackModel.sizePolicy().hasHeightForWidth())
        TrackModel.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=TrackModel)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabs.setAutoFillBackground(False)
        self.tabs.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(204, 204, 204);")
        self.tabs.setDocumentMode(True)
        self.tabs.setTabsClosable(False)
        self.tabs.setTabBarAutoHide(False)
        self.tabs.setObjectName("tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.tempStepper = QtWidgets.QSpinBox(parent=self.tab)
        self.tempStepper.setStyleSheet("font: 20pt \"Times New Roman\";")
        self.tempStepper.setWrapping(False)
        self.tempStepper.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tempStepper.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.tempStepper.setAccelerated(False)
        self.tempStepper.setMinimum(-50)
        self.tempStepper.setMaximum(150)
        self.tempStepper.setProperty("value", 40)
        self.tempStepper.setObjectName("tempStepper")
        self.gridLayout_16.addWidget(self.tempStepper, 2, 0, 1, 1)
        self.tempLabel = QtWidgets.QLabel(parent=self.tab)
        self.tempLabel.setStyleSheet("font: 30pt \"Times New Roman\";")
        self.tempLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tempLabel.setObjectName("tempLabel")
        self.gridLayout_16.addWidget(self.tempLabel, 1, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_16, 8, 0, 1, 1)
        self.tab1Label = QtWidgets.QLabel(parent=self.tab)
        self.tab1Label.setStyleSheet("font: 40pt \"Times New Roman\";\n"
"background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.tab1Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tab1Label.setObjectName("tab1Label")
        self.gridLayout_14.addWidget(self.tab1Label, 0, 0, 2, 2)
        self.trackLayout_header = QtWidgets.QFrame(parent=self.tab)
        self.trackLayout_header.setObjectName("trackLayout_header")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.trackLayout_header)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.trackLayout_header)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.blockInfo = QtWidgets.QTableWidget(parent=self.trackLayout_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blockInfo.sizePolicy().hasHeightForWidth())
        self.blockInfo.setSizePolicy(sizePolicy)
        self.blockInfo.setMinimumSize(QtCore.QSize(0, 192))
        self.blockInfo.setMaximumSize(QtCore.QSize(16777215, 192))
        self.blockInfo.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.blockInfo.setAutoScroll(True)
        self.blockInfo.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.blockInfo.setAlternatingRowColors(False)
        self.blockInfo.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.blockInfo.setShowGrid(True)
        self.blockInfo.setWordWrap(True)
        self.blockInfo.setCornerButtonEnabled(False)
        self.blockInfo.setRowCount(1)
        self.blockInfo.setColumnCount(10)
        self.blockInfo.setObjectName("blockInfo")
        item = QtWidgets.QTableWidgetItem()
        self.blockInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.blockInfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.blockInfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.blockInfo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.blockInfo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.blockInfo.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.blockInfo.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.blockInfo.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.blockInfo.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.blockInfo.setHorizontalHeaderItem(9, item)
        self.blockInfo.horizontalHeader().setVisible(True)
        self.blockInfo.horizontalHeader().setCascadingSectionResizes(False)
        self.blockInfo.horizontalHeader().setDefaultSectionSize(156)
        self.blockInfo.horizontalHeader().setHighlightSections(True)
        self.blockInfo.verticalHeader().setVisible(False)
        self.blockInfo.verticalHeader().setHighlightSections(True)
        self.blockInfo.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_3.addWidget(self.blockInfo)
        self.gridLayout_14.addWidget(self.trackLayout_header, 2, 0, 1, 2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fileUploadButton = QtWidgets.QPushButton(parent=self.tab)
        self.fileUploadButton.setStyleSheet("font: 30pt \"Times New Roman\";")
        self.fileUploadButton.setAutoDefault(False)
        self.fileUploadButton.setDefault(False)
        self.fileUploadButton.setFlat(False)
        self.fileUploadButton.setObjectName("fileUploadButton")
        self.verticalLayout_6.addWidget(self.fileUploadButton)
        self.gridLayout_14.addLayout(self.verticalLayout_6, 8, 1, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.verticalLayout_11.addLayout(self.formLayout_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_7.addLayout(self.verticalLayout_12)
        self.verticalLayout_11.addLayout(self.verticalLayout_7)
        self.gridLayout_14.addLayout(self.verticalLayout_11, 4, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(parent=self.tab)
        self.label_2.setStyleSheet("font: 10pt \"Times New Roman\";\n"
"background-color: rgb(68, 68, 68);\n"
"color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_14.addWidget(self.label_2, 3, 0, 1, 1)
        self.tabs.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(parent=self.tab_3)
        self.label.setStyleSheet("font: 40pt \"Times New Roman\";\n"
"background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.failures = QtWidgets.QFrame(parent=self.tab_3)
        self.failures.setObjectName("failures")
        self.murphy_header = QtWidgets.QVBoxLayout(self.failures)
        self.murphy_header.setObjectName("murphy_header")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.circuitFailureLabel = QtWidgets.QLabel(parent=self.failures)
        self.circuitFailureLabel.setStyleSheet("font: 36pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.circuitFailureLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.circuitFailureLabel.setObjectName("circuitFailureLabel")
        self.horizontalLayout_3.addWidget(self.circuitFailureLabel)
        self.comboBox1 = QtWidgets.QComboBox(parent=self.failures)
        self.comboBox1.setObjectName("comboBox1")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox1)
        self.breakButton1 = QtWidgets.QPushButton(parent=self.failures)
        self.breakButton1.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.breakButton1.setObjectName("breakButton1")
        self.horizontalLayout_3.addWidget(self.breakButton1)
        self.murphy_header.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.powerFailureLabel = QtWidgets.QLabel(parent=self.failures)
        self.powerFailureLabel.setStyleSheet("font: 36pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.powerFailureLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.powerFailureLabel.setObjectName("powerFailureLabel")
        self.horizontalLayout_6.addWidget(self.powerFailureLabel)
        self.comboBox2 = QtWidgets.QComboBox(parent=self.failures)
        self.comboBox2.setObjectName("comboBox2")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox2)
        self.breakButton2 = QtWidgets.QPushButton(parent=self.failures)
        self.breakButton2.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.breakButton2.setObjectName("breakButton2")
        self.horizontalLayout_6.addWidget(self.breakButton2)
        self.murphy_header.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.railFailureLabel = QtWidgets.QLabel(parent=self.failures)
        self.railFailureLabel.setStyleSheet("font: 36pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.railFailureLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.railFailureLabel.setObjectName("railFailureLabel")
        self.horizontalLayout_7.addWidget(self.railFailureLabel)
        self.comboBox3 = QtWidgets.QComboBox(parent=self.failures)
        self.comboBox3.setObjectName("comboBox3")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox3)
        self.breakButton3 = QtWidgets.QPushButton(parent=self.failures)
        self.breakButton3.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.breakButton3.setObjectName("breakButton3")
        self.horizontalLayout_7.addWidget(self.breakButton3)
        self.murphy_header.addLayout(self.horizontalLayout_7)
        self.gridLayout_2.addWidget(self.failures, 1, 0, 1, 1)
        self.tabs.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.applyChangesButton = QtWidgets.QPushButton(parent=self.tab_2)
        self.applyChangesButton.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.applyChangesButton.setObjectName("applyChangesButton")
        self.gridLayout_19.addWidget(self.applyChangesButton, 4, 0, 1, 2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.switchTable = QtWidgets.QTableWidget(parent=self.tab_2)
        self.switchTable.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.switchTable.setRowCount(1)
        self.switchTable.setColumnCount(2)
        self.switchTable.setObjectName("switchTable")
        item = QtWidgets.QTableWidgetItem()
        self.switchTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.switchTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.switchTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.switchTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.switchTable.setItem(0, 1, item)
        self.switchTable.horizontalHeader().setDefaultSectionSize(110)
        self.verticalLayout_9.addWidget(self.switchTable)
        self.lightTable = QtWidgets.QTableWidget(parent=self.tab_2)
        self.lightTable.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.lightTable.setObjectName("lightTable")
        self.lightTable.setColumnCount(2)
        self.lightTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.lightTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lightTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lightTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lightTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lightTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lightTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lightTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lightTable.setItem(1, 1, item)
        self.lightTable.horizontalHeader().setDefaultSectionSize(110)
        self.verticalLayout_9.addWidget(self.lightTable)
        self.crossingTable = QtWidgets.QTableWidget(parent=self.tab_2)
        self.crossingTable.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.crossingTable.setObjectName("crossingTable")
        self.crossingTable.setColumnCount(3)
        self.crossingTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.crossingTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.crossingTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.crossingTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.crossingTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.crossingTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.crossingTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.crossingTable.setItem(0, 2, item)
        self.crossingTable.horizontalHeader().setDefaultSectionSize(73)
        self.verticalLayout_9.addWidget(self.crossingTable)
        self.passInfoTable = QtWidgets.QTableWidget(parent=self.tab_2)
        self.passInfoTable.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.passInfoTable.setObjectName("passInfoTable")
        self.passInfoTable.setColumnCount(3)
        self.passInfoTable.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.passInfoTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout_9.addWidget(self.passInfoTable)
        self.gridLayout_19.addLayout(self.verticalLayout_9, 3, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_3.setStyleSheet("font: 20pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.positionValue = QtWidgets.QDoubleSpinBox(parent=self.tab_2)
        self.positionValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.positionValue.setObjectName("positionValue")
        self.verticalLayout_2.addWidget(self.positionValue)
        self.gridLayout_19.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.stationPicker = QtWidgets.QComboBox(parent=self.tab_2)
        self.stationPicker.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.stationPicker.setObjectName("stationPicker")
        self.stationPicker.addItem("")
        self.stationPicker.addItem("")
        self.stationPicker.addItem("")
        self.gridLayout_19.addWidget(self.stationPicker, 1, 1, 1, 1)
        self.beaconLabel = QtWidgets.QLabel(parent=self.tab_2)
        self.beaconLabel.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.beaconLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.beaconLabel.setObjectName("beaconLabel")
        self.gridLayout_19.addWidget(self.beaconLabel, 0, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(parent=self.tab_2)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_19.addWidget(self.textEdit, 2, 1, 2, 1)
        self.tabs.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabs)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        TrackModel.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=TrackModel)
        self.statusbar.setObjectName("statusbar")
        TrackModel.setStatusBar(self.statusbar)

        self.retranslateUi(TrackModel)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TrackModel)

    def retranslateUi(self, TrackModel):
        _translate = QtCore.QCoreApplication.translate
        TrackModel.setWindowTitle(_translate("TrackModel", "MainWindow"))
        self.tempStepper.setSuffix(_translate("TrackModel", " F"))
        self.tempLabel.setText(_translate("TrackModel", "Rail Temperature"))
        self.tab1Label.setText(_translate("TrackModel", "Track Layout"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TrackModel", "Line"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TrackModel", "Section"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TrackModel", "Number"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TrackModel", "Length"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TrackModel", "Grade"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TrackModel", "Speed Limit"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TrackModel", "Infrastructure"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("TrackModel", "Elevation"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("TrackModel", "Cumulative Elevation"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("TrackModel", "Occupancy"))
        item = self.blockInfo.horizontalHeaderItem(0)
        item.setText(_translate("TrackModel", "Line"))
        item = self.blockInfo.horizontalHeaderItem(1)
        item.setText(_translate("TrackModel", "Section"))
        item = self.blockInfo.horizontalHeaderItem(2)
        item.setText(_translate("TrackModel", "Number"))
        item = self.blockInfo.horizontalHeaderItem(3)
        item.setText(_translate("TrackModel", "Length (ft)"))
        item = self.blockInfo.horizontalHeaderItem(4)
        item.setText(_translate("TrackModel", "Grade (%)"))
        item = self.blockInfo.horizontalHeaderItem(5)
        item.setText(_translate("TrackModel", "Station Side"))
        item = self.blockInfo.horizontalHeaderItem(6)
        item.setText(_translate("TrackModel", "Elevation (ft)"))
        item = self.blockInfo.horizontalHeaderItem(7)
        item.setText(_translate("TrackModel", "Cumulative Elevation (ft)"))
        item = self.blockInfo.horizontalHeaderItem(8)
        item.setText(_translate("TrackModel", "Speed Limit (mph)"))
        item = self.blockInfo.horizontalHeaderItem(9)
        item.setText(_translate("TrackModel", "Failure"))
        self.fileUploadButton.setText(_translate("TrackModel", "Upload New Layout"))
        self.label_2.setText(_translate("TrackModel", "Track Heater"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("TrackModel", "Track Layout"))
        self.label.setText(_translate("TrackModel", "Murphy\'s View"))
        self.circuitFailureLabel.setText(_translate("TrackModel", "Circuit Failure: "))
        self.comboBox1.setItemText(0, _translate("TrackModel", "1"))
        self.comboBox1.setItemText(1, _translate("TrackModel", "2"))
        self.comboBox1.setItemText(2, _translate("TrackModel", "3"))
        self.comboBox1.setItemText(3, _translate("TrackModel", "4"))
        self.comboBox1.setItemText(4, _translate("TrackModel", "5"))
        self.comboBox1.setItemText(5, _translate("TrackModel", "6"))
        self.comboBox1.setItemText(6, _translate("TrackModel", "7"))
        self.comboBox1.setItemText(7, _translate("TrackModel", "8"))
        self.comboBox1.setItemText(8, _translate("TrackModel", "9"))
        self.comboBox1.setItemText(9, _translate("TrackModel", "10"))
        self.comboBox1.setItemText(10, _translate("TrackModel", "11"))
        self.comboBox1.setItemText(11, _translate("TrackModel", "12"))
        self.comboBox1.setItemText(12, _translate("TrackModel", "13"))
        self.comboBox1.setItemText(13, _translate("TrackModel", "14"))
        self.comboBox1.setItemText(14, _translate("TrackModel", "15"))
        self.breakButton1.setText(_translate("TrackModel", "BREAK"))
        self.powerFailureLabel.setText(_translate("TrackModel", "Power Failure: "))
        self.comboBox2.setItemText(0, _translate("TrackModel", "1"))
        self.comboBox2.setItemText(1, _translate("TrackModel", "2"))
        self.comboBox2.setItemText(2, _translate("TrackModel", "3"))
        self.comboBox2.setItemText(3, _translate("TrackModel", "4"))
        self.comboBox2.setItemText(4, _translate("TrackModel", "5"))
        self.comboBox2.setItemText(5, _translate("TrackModel", "6"))
        self.comboBox2.setItemText(6, _translate("TrackModel", "7"))
        self.comboBox2.setItemText(7, _translate("TrackModel", "8"))
        self.comboBox2.setItemText(8, _translate("TrackModel", "9"))
        self.comboBox2.setItemText(9, _translate("TrackModel", "10"))
        self.comboBox2.setItemText(10, _translate("TrackModel", "11"))
        self.comboBox2.setItemText(11, _translate("TrackModel", "12"))
        self.comboBox2.setItemText(12, _translate("TrackModel", "13"))
        self.comboBox2.setItemText(13, _translate("TrackModel", "14"))
        self.comboBox2.setItemText(14, _translate("TrackModel", "15"))
        self.breakButton2.setText(_translate("TrackModel", "BREAK"))
        self.railFailureLabel.setText(_translate("TrackModel", "Rail Failure: "))
        self.comboBox3.setItemText(0, _translate("TrackModel", "1"))
        self.comboBox3.setItemText(1, _translate("TrackModel", "2"))
        self.comboBox3.setItemText(2, _translate("TrackModel", "3"))
        self.comboBox3.setItemText(3, _translate("TrackModel", "4"))
        self.comboBox3.setItemText(4, _translate("TrackModel", "5"))
        self.comboBox3.setItemText(5, _translate("TrackModel", "6"))
        self.comboBox3.setItemText(6, _translate("TrackModel", "7"))
        self.comboBox3.setItemText(7, _translate("TrackModel", "8"))
        self.comboBox3.setItemText(8, _translate("TrackModel", "9"))
        self.comboBox3.setItemText(9, _translate("TrackModel", "10"))
        self.comboBox3.setItemText(10, _translate("TrackModel", "11"))
        self.comboBox3.setItemText(11, _translate("TrackModel", "12"))
        self.comboBox3.setItemText(12, _translate("TrackModel", "13"))
        self.comboBox3.setItemText(13, _translate("TrackModel", "14"))
        self.comboBox3.setItemText(14, _translate("TrackModel", "15"))
        self.breakButton3.setText(_translate("TrackModel", "BREAK"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), _translate("TrackModel", "Murphy\'s View"))
        self.applyChangesButton.setText(_translate("TrackModel", "Apply Changes"))
        item = self.switchTable.verticalHeaderItem(0)
        item.setText(_translate("TrackModel", "1"))
        item = self.switchTable.horizontalHeaderItem(0)
        item.setText(_translate("TrackModel", "Switch Location"))
        item = self.switchTable.horizontalHeaderItem(1)
        item.setText(_translate("TrackModel", "Switch State"))
        __sortingEnabled = self.switchTable.isSortingEnabled()
        self.switchTable.setSortingEnabled(False)
        item = self.switchTable.item(0, 0)
        item.setText(_translate("TrackModel", "Block 5"))
        item = self.switchTable.item(0, 1)
        item.setText(_translate("TrackModel", "(5 to 6)"))
        self.switchTable.setSortingEnabled(__sortingEnabled)
        item = self.lightTable.verticalHeaderItem(0)
        item.setText(_translate("TrackModel", "1"))
        item = self.lightTable.verticalHeaderItem(1)
        item.setText(_translate("TrackModel", "2"))
        item = self.lightTable.horizontalHeaderItem(0)
        item.setText(_translate("TrackModel", "Traffic Light Location"))
        item = self.lightTable.horizontalHeaderItem(1)
        item.setText(_translate("TrackModel", "Light State"))
        __sortingEnabled = self.lightTable.isSortingEnabled()
        self.lightTable.setSortingEnabled(False)
        item = self.lightTable.item(0, 0)
        item.setText(_translate("TrackModel", "Block 6"))
        item = self.lightTable.item(0, 1)
        item.setText(_translate("TrackModel", "Green"))
        item = self.lightTable.item(1, 0)
        item.setText(_translate("TrackModel", "Block 11"))
        item = self.lightTable.item(1, 1)
        item.setText(_translate("TrackModel", "Red"))
        self.lightTable.setSortingEnabled(__sortingEnabled)
        item = self.crossingTable.verticalHeaderItem(0)
        item.setText(_translate("TrackModel", "1"))
        item = self.crossingTable.horizontalHeaderItem(0)
        item.setText(_translate("TrackModel", "Crossing Location"))
        item = self.crossingTable.horizontalHeaderItem(1)
        item.setText(_translate("TrackModel", "Light State"))
        item = self.crossingTable.horizontalHeaderItem(2)
        item.setText(_translate("TrackModel", "Gate State"))
        __sortingEnabled = self.crossingTable.isSortingEnabled()
        self.crossingTable.setSortingEnabled(False)
        item = self.crossingTable.item(0, 0)
        item.setText(_translate("TrackModel", "Block 3"))
        item = self.crossingTable.item(0, 1)
        item.setText(_translate("TrackModel", "Green"))
        item = self.crossingTable.item(0, 2)
        item.setText(_translate("TrackModel", "Open"))
        self.crossingTable.setSortingEnabled(__sortingEnabled)
        item = self.passInfoTable.verticalHeaderItem(0)
        item.setText(_translate("TrackModel", "Block 1"))
        item = self.passInfoTable.verticalHeaderItem(1)
        item.setText(_translate("TrackModel", "Block 2"))
        item = self.passInfoTable.verticalHeaderItem(2)
        item.setText(_translate("TrackModel", "Block 3"))
        item = self.passInfoTable.verticalHeaderItem(3)
        item.setText(_translate("TrackModel", "Block 4"))
        item = self.passInfoTable.verticalHeaderItem(4)
        item.setText(_translate("TrackModel", "Block 5"))
        item = self.passInfoTable.verticalHeaderItem(5)
        item.setText(_translate("TrackModel", "Block 6"))
        item = self.passInfoTable.verticalHeaderItem(6)
        item.setText(_translate("TrackModel", "Block 7"))
        item = self.passInfoTable.verticalHeaderItem(7)
        item.setText(_translate("TrackModel", "Block 8"))
        item = self.passInfoTable.verticalHeaderItem(8)
        item.setText(_translate("TrackModel", "Block 9"))
        item = self.passInfoTable.verticalHeaderItem(9)
        item.setText(_translate("TrackModel", "Block 10"))
        item = self.passInfoTable.verticalHeaderItem(10)
        item.setText(_translate("TrackModel", "Block 11"))
        item = self.passInfoTable.verticalHeaderItem(11)
        item.setText(_translate("TrackModel", "Block 12"))
        item = self.passInfoTable.verticalHeaderItem(12)
        item.setText(_translate("TrackModel", "Block 13"))
        item = self.passInfoTable.verticalHeaderItem(13)
        item.setText(_translate("TrackModel", "Block 14"))
        item = self.passInfoTable.verticalHeaderItem(14)
        item.setText(_translate("TrackModel", "Block 15"))
        item = self.passInfoTable.horizontalHeaderItem(0)
        item.setText(_translate("TrackModel", "Commanded Speed"))
        item = self.passInfoTable.horizontalHeaderItem(1)
        item.setText(_translate("TrackModel", "Authority"))
        item = self.passInfoTable.horizontalHeaderItem(2)
        item.setText(_translate("TrackModel", "Vacancy"))
        self.label_3.setText(_translate("TrackModel", "Position"))
        self.positionValue.setSuffix(_translate("TrackModel", " m"))
        self.stationPicker.setItemText(0, _translate("TrackModel", "Station A"))
        self.stationPicker.setItemText(1, _translate("TrackModel", "Station B"))
        self.stationPicker.setItemText(2, _translate("TrackModel", "Station C"))
        self.beaconLabel.setText(_translate("TrackModel", "Beacon Information"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _translate("TrackModel", "Testbench"))
