import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../')))

from CTC_Office.CTC_logic import CTC_logic
from TrainModel.CTC_communicate import CTC_Train_Model_Communicate
from Resources.CTCWaysideComm import CTCWaysideControllerComm
from Resources.CTCTrain import CTCTrain

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QFileDialog

import datetime as dt
import time

class CTC_frontend(object):
    def __init__(self, ctc_train_communicate: CTCTrain, wayside_communicate: CTCWaysideControllerComm):
        self.ctc = CTC_logic(ctc_train_communicate, wayside_communicate)
        self.wayside_communicate = wayside_communicate
        self.ctc_train_communicate = ctc_train_communicate
        
        

        self.wayside_communicate.block_occupancy_signal.connect(self.update_block_occupancies)
        self.wall_clock_time = dt.datetime.now()

    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(838, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainwindow.sizePolicy().hasHeightForWidth())
        mainwindow.setSizePolicy(sizePolicy)
        mainwindow.setMaximumSize(QtCore.QSize(900000, 1000))
        font = QtGui.QFont()
        font.setFamily("Arial")
        mainwindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pagetab = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.pagetab.setMaximumSize(QtCore.QSize(10000000, 750))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pagetab.setFont(font)
        self.pagetab.setObjectName("pagetab")
        self.TrainTab = QtWidgets.QWidget()
        self.TrainTab.setObjectName("TrainTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.TrainTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.InfoLayout = QtWidgets.QGridLayout()
        self.InfoLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.InfoLayout.setContentsMargins(-1, 0, -1, -1)
        self.InfoLayout.setObjectName("InfoLayout")
        self.ThroughputFrame = QtWidgets.QFrame(parent=self.TrainTab)
        self.ThroughputFrame.setMinimumSize(QtCore.QSize(175, 170))
        self.ThroughputFrame.setMaximumSize(QtCore.QSize(200, 170))
        self.ThroughputFrame.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border: 2px solid;\n"
"")
        self.ThroughputFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ThroughputFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ThroughputFrame.setObjectName("ThroughputFrame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.ThroughputFrame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 171, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.ThroughputLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.ThroughputLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.ThroughputLayout.setContentsMargins(10, 10, 10, 10)
        self.ThroughputLayout.setSpacing(10)
        self.ThroughputLayout.setObjectName("ThroughputLayout")
        self.TimeLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.TimeLabel.setMaximumSize(QtCore.QSize(120, 60))
        self.TimeLabel.setStyleSheet("font: 36pt \"Arial\";")
        self.TimeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TimeLabel.setObjectName("TimeLabel")
        self.ThroughputLayout.addWidget(self.TimeLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.ThroughputDisplay = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.ThroughputDisplay.setMinimumSize(QtCore.QSize(150, 40))
        self.ThroughputDisplay.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ThroughputDisplay.setFont(font)
        self.ThroughputDisplay.setStyleSheet("border: 2px;\n"
"border-color: rgb(0, 0, 0);\n"
"font: 18pt \"Arial\";\n"
"background-color: rgb(43, 120, 228);\n"
"")
        self.ThroughputDisplay.setLineWidth(4)
        self.ThroughputDisplay.setMidLineWidth(4)
        self.ThroughputDisplay.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ThroughputDisplay.setObjectName("ThroughputDisplay")
        self.ThroughputLayout.addWidget(self.ThroughputDisplay, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ThroughputLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.ThroughputLabel.setMaximumSize(QtCore.QSize(100, 40))
        self.ThroughputLabel.setStyleSheet("font: 14pt \"Arial\";\n"
"border:0px\n"
";")
        self.ThroughputLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.ThroughputLabel.setObjectName("ThroughputLabel")
        self.ThroughputLayout.addWidget(self.ThroughputLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.UploadScheduleButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.UploadScheduleButton.setMinimumSize(QtCore.QSize(150, 30))
        self.UploadScheduleButton.setMaximumSize(QtCore.QSize(200, 40))
        self.UploadScheduleButton.setStyleSheet("background-color: rgb(255, 0, 255);\n"
"border: 1px solid;\n"
"font: 18pt \"Arial\";\n"
"")
        self.UploadScheduleButton.setObjectName("UploadScheduleButton")
        self.UploadScheduleButton.clicked.connect(self.upload_layout)
        self.ThroughputLayout.addWidget(self.UploadScheduleButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.InfoLayout.addWidget(self.ThroughputFrame, 2, 1, 1, 1)
        self.TrainTable = QtWidgets.QTabWidget(parent=self.TrainTab)
        self.TrainTable.setMinimumSize(QtCore.QSize(0, 200))
        self.TrainTable.setMaximumSize(QtCore.QSize(800, 400))
        self.TrainTable.setStyleSheet("")
        self.TrainTable.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.TrainTable.setUsesScrollButtons(False)
        self.TrainTable.setTabsClosable(False)
        self.TrainTable.setTabBarAutoHide(True)
        self.TrainTable.setObjectName("TrainTable")
        self.BlueLineTrainsTab = QtWidgets.QWidget()
        self.BlueLineTrainsTab.setObjectName("BlueLineTrainsTab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.BlueLineTrainsTab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(-1, 9, 751, 361))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.BlueTrainsLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.BlueTrainsLayout.setContentsMargins(0, 0, 0, 0)
        self.BlueTrainsLayout.setObjectName("BlueTrainsLayout")
        self.BlueTrainsTable = QtWidgets.QTableWidget(parent=self.gridLayoutWidget_2)
        self.BlueTrainsTable.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.BlueTrainsTable.sizePolicy().hasHeightForWidth())
        self.BlueTrainsTable.setSizePolicy(sizePolicy)
        self.BlueTrainsTable.setMinimumSize(QtCore.QSize(0, 100))
        self.BlueTrainsTable.setMaximumSize(QtCore.QSize(750, 600))
        self.BlueTrainsTable.setStyleSheet("font: 13pt \"Arial\";")
        self.BlueTrainsTable.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.BlueTrainsTable.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.BlueTrainsTable.setLineWidth(2)
        self.BlueTrainsTable.setMidLineWidth(0)
        self.BlueTrainsTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.BlueTrainsTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.BlueTrainsTable.setShowGrid(True)
        self.BlueTrainsTable.setRowCount(0)
        self.BlueTrainsTable.setObjectName("BlueTrainsTable")
        self.BlueTrainsTable.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable.setHorizontalHeaderItem(4, item)
        self.BlueTrainsTable.horizontalHeader().setCascadingSectionResizes(True)
        self.BlueTrainsTable.horizontalHeader().setDefaultSectionSize(143)
        self.BlueTrainsTable.horizontalHeader().setHighlightSections(True)
        self.BlueTrainsTable.horizontalHeader().setMinimumSectionSize(22)
        self.BlueTrainsTable.horizontalHeader().setSortIndicatorShown(False)
        self.BlueTrainsTable.horizontalHeader().setStretchLastSection(False)
        self.BlueTrainsTable.verticalHeader().setVisible(False)
        self.BlueTrainsLayout.addWidget(self.BlueTrainsTable, 0, 0, 1, 1)
        self.TrainTable.addTab(self.BlueLineTrainsTab, "")
        self.RedLineTrainsTab = QtWidgets.QWidget()
        self.RedLineTrainsTab.setObjectName("RedLineTrainsTab")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(parent=self.RedLineTrainsTab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 721, 361))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.BlueTrainsLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.BlueTrainsLayout_2.setContentsMargins(0, 0, 0, 0)
        self.BlueTrainsLayout_2.setObjectName("BlueTrainsLayout_2")
        self.BlueTrainsTable_2 = QtWidgets.QTableWidget(parent=self.gridLayoutWidget_3)
        self.BlueTrainsTable_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.BlueTrainsTable_2.sizePolicy().hasHeightForWidth())
        self.BlueTrainsTable_2.setSizePolicy(sizePolicy)
        self.BlueTrainsTable_2.setMinimumSize(QtCore.QSize(0, 100))
        self.BlueTrainsTable_2.setMaximumSize(QtCore.QSize(720, 600))
        self.BlueTrainsTable_2.setStyleSheet("font: 13pt \"Arial\";")
        self.BlueTrainsTable_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.BlueTrainsTable_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.BlueTrainsTable_2.setLineWidth(2)
        self.BlueTrainsTable_2.setMidLineWidth(0)
        self.BlueTrainsTable_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.BlueTrainsTable_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.BlueTrainsTable_2.setShowGrid(True)
        self.BlueTrainsTable_2.setRowCount(0)
        self.BlueTrainsTable_2.setObjectName("BlueTrainsTable_2")
        self.BlueTrainsTable_2.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable_2.setHorizontalHeaderItem(4, item)
        self.BlueTrainsTable_2.horizontalHeader().setCascadingSectionResizes(True)
        self.BlueTrainsTable_2.horizontalHeader().setDefaultSectionSize(143)
        self.BlueTrainsTable_2.horizontalHeader().setHighlightSections(True)
        self.BlueTrainsTable_2.horizontalHeader().setMinimumSectionSize(22)
        self.BlueTrainsTable_2.horizontalHeader().setSortIndicatorShown(False)
        self.BlueTrainsTable_2.horizontalHeader().setStretchLastSection(False)
        self.BlueTrainsTable_2.verticalHeader().setVisible(False)
        self.BlueTrainsLayout_2.addWidget(self.BlueTrainsTable_2, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.TrainTable.addTab(self.RedLineTrainsTab, "")
        self.GreenLineTrainsTab = QtWidgets.QWidget()
        self.GreenLineTrainsTab.setObjectName("GreenLineTrainsTab")
        self.TrainTable.addTab(self.GreenLineTrainsTab, "")
        self.InfoLayout.addWidget(self.TrainTable, 4, 0, 1, 2)
        self.automatic_manual_toggle = QtWidgets.QPushButton(parent=self.TrainTab)
        self.automatic_manual_toggle.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.automatic_manual_toggle.setFont(font)
        self.automatic_manual_toggle.setStyleSheet("background-color: rgb(255, 143, 27);")
        self.automatic_manual_toggle.setObjectName("automatic_manual_toggle")
        self.automatic_manual_toggle.clicked.connect(self.auto_manual_toggle)
        self.InfoLayout.addWidget(self.automatic_manual_toggle, 3, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ScheduleFrame = QtWidgets.QFrame(parent=self.TrainTab)
        self.ScheduleFrame.setMinimumSize(QtCore.QSize(570, 200))
        self.ScheduleFrame.setMaximumSize(QtCore.QSize(600, 16777215))
        self.ScheduleFrame.setStyleSheet("border: 2px solid #000000;")
        self.ScheduleFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ScheduleFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ScheduleFrame.setObjectName("ScheduleFrame")
        self.ScheduleTitle = QtWidgets.QLabel(parent=self.ScheduleFrame)
        self.ScheduleTitle.setGeometry(QtCore.QRect(10, 10, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.ScheduleTitle.setFont(font)
        self.ScheduleTitle.setStyleSheet("border: 0px;")
        self.ScheduleTitle.setObjectName("ScheduleTitle")
        self.DepartureSelector = QtWidgets.QTimeEdit(parent=self.ScheduleFrame)
        self.DepartureSelector.setDisplayFormat("HH:mm")
        self.DepartureSelector.setTime(QtCore.QTime.currentTime())
        self.DepartureSelector.setGeometry(QtCore.QRect(370, 60, 101, 24))
        self.DepartureSelector.setStyleSheet("font: 13pt \"Arial\";")
        self.DepartureSelector.setObjectName("DepartureSelector")
        self.destinationLabel = QtWidgets.QLabel(parent=self.ScheduleFrame)
        self.destinationLabel.setGeometry(QtCore.QRect(200, 100, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.destinationLabel.setFont(font)
        self.destinationLabel.setStyleSheet("border: 0px;")
        self.destinationLabel.setObjectName("destinationLabel")
        self.departureLabel = QtWidgets.QLabel(parent=self.ScheduleFrame)
        self.departureLabel.setGeometry(QtCore.QRect(200, 50, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.departureLabel.setFont(font)
        self.departureLabel.setStyleSheet("border: 0px;")
        self.departureLabel.setObjectName("departureLabel")
        self.StationSelector = QtWidgets.QComboBox(parent=self.ScheduleFrame)
        self.StationSelector.setGeometry(QtCore.QRect(370, 110, 191, 26))
        self.StationSelector.setObjectName("StationSelector")
        self.ArrivalLabel = QtWidgets.QLabel(parent=self.ScheduleFrame)
        self.ArrivalLabel.setGeometry(QtCore.QRect(200, 150, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.ArrivalLabel.setFont(font)
        self.ArrivalLabel.setStyleSheet("border: 0px;")
        self.ArrivalLabel.setObjectName("ArrivalLabel")
        self.ArrivalSelector = QtWidgets.QTimeEdit(parent=self.ScheduleFrame)
        self.ArrivalSelector.setGeometry(QtCore.QRect(310, 160, 101, 24))
        self.ArrivalSelector.setStyleSheet("font: 13pt \"Arial\";")
        self.ArrivalSelector.setObjectName("ArrivalSelector")
        self.DispatchButton = QtWidgets.QPushButton(parent=self.ScheduleFrame)
        self.DispatchButton.setGeometry(QtCore.QRect(370, 10, 151, 32))
        self.DispatchButton.setStyleSheet("background-color: rgb(70, 158, 49);\n"
"font: 18pt \"Arial\";\n"
"border: 1px solid;\n"
"")
        self.DispatchButton.setCheckable(False)
        self.DispatchButton.setObjectName("DispatchButton")
        self.DispatchButton.clicked.connect(self.dispatch_train)
        self.LineLabel = QtWidgets.QLabel(parent=self.ScheduleFrame)
        self.LineLabel.setGeometry(QtCore.QRect(10, 50, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.LineLabel.setFont(font)
        self.LineLabel.setStyleSheet("border: 0px;")
        self.LineLabel.setObjectName("LineLabel")
        self.train_vew_line_selector = QtWidgets.QComboBox(parent=self.ScheduleFrame)
        self.train_vew_line_selector.setGeometry(QtCore.QRect(80, 50, 100, 40))
        self.train_vew_line_selector.setMinimumSize(QtCore.QSize(90, 0))
        self.train_vew_line_selector.setMaximumSize(QtCore.QSize(100, 40))
        self.train_vew_line_selector.setStyleSheet("font: 18pt \"Arial\";")
        self.train_vew_line_selector.setObjectName("train_vew_line_selector")
        self.train_vew_line_selector.addItem("")
        self.train_vew_line_selector.addItem("")
        self.train_vew_line_selector.addItem("")
        self.add_destination_button = QtWidgets.QPushButton(parent=self.ScheduleFrame)
        self.add_destination_button.setGeometry(QtCore.QRect(420, 160, 141, 32))
        self.add_destination_button.setStyleSheet("background-color: rgb(133, 239, 128);\n"
"font: 18pt \"Arial\";\n"
"border: 1px solid;\n"
"")
        self.add_destination_button.setCheckable(False)
        self.add_destination_button.setObjectName("add_destination_button")
        self.add_destination_button.clicked.connect(self.add_destination)
        self.destination_list_label = QtWidgets.QLabel(parent=self.ScheduleFrame)
        self.destination_list_label.setGeometry(QtCore.QRect(10, 100, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.destination_list_label.setFont(font)
        self.destination_list_label.setStyleSheet("border: 0px;")
        self.destination_list_label.setObjectName("destination_list_label")
        self.destination_scroll_area = QtWidgets.QScrollArea(parent=self.ScheduleFrame)
        self.destination_scroll_area.setGeometry(QtCore.QRect(10, 130, 171, 71))
        self.destination_scroll_area.setWidgetResizable(True)
        self.destination_scroll_area.setObjectName("destination_scroll_area")
        self.scroll_area_contents = QtWidgets.QWidget()
        self.scroll_area_contents.setGeometry(QtCore.QRect(0, 0, 167, 67))
        self.scroll_area_contents.setObjectName("scroll_area_contents")
        self.destination_list = QtWidgets.QListView(parent=self.scroll_area_contents)
        self.destination_list.setGeometry(QtCore.QRect(-10, -10, 181, 81))
        self.destination_list.setStyleSheet("font: 13pt \"Arial\";")
        self.destination_list.setObjectName("destination_list")
        self.destination_scroll_area.setWidget(self.scroll_area_contents)
        self.InfoLayout.addWidget(self.ScheduleFrame, 2, 0, 2, 1)
        self.HeaderFrame = QtWidgets.QFrame(parent=self.TrainTab)
        self.HeaderFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.HeaderFrame.setFont(font)
        self.HeaderFrame.setStyleSheet("background-color: rgb(75, 120, 228);")
        self.HeaderFrame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.HeaderFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.HeaderFrame.setObjectName("HeaderFrame")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.HeaderFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 761, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.HeaderLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.HeaderLayout.setContentsMargins(0, 0, 0, 0)
        self.HeaderLayout.setObjectName("HeaderLayout")
        self.HeaderLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.HeaderLabel.setFont(font)
        self.HeaderLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.HeaderLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.HeaderLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.HeaderLabel.setObjectName("HeaderLabel")
        self.HeaderLayout.addWidget(self.HeaderLabel)
        self.InfoLayout.addWidget(self.HeaderFrame, 0, 0, 2, 2)
        self.gridLayout_3.addLayout(self.InfoLayout, 1, 0, 1, 1)
        self.pagetab.addTab(self.TrainTab, "")
        self.BlockTab = QtWidgets.QWidget()
        self.BlockTab.setObjectName("BlockTab")
        self.frame = QtWidgets.QFrame(parent=self.BlockTab)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 821, 691))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(parent=self.frame)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(1, 0, 801, 691))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.InfoLayout_pg2 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.InfoLayout_pg2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.InfoLayout_pg2.setContentsMargins(-1, 0, -1, -1)
        self.InfoLayout_pg2.setHorizontalSpacing(10)
        self.InfoLayout_pg2.setObjectName("InfoLayout_pg2")
        self.ThroughputFrame_pg2 = QtWidgets.QFrame(parent=self.gridLayoutWidget_5)
        self.ThroughputFrame_pg2.setMinimumSize(QtCore.QSize(175, 150))
        self.ThroughputFrame_pg2.setMaximumSize(QtCore.QSize(200, 150))
        self.ThroughputFrame_pg2.setStyleSheet("border: 2px solid #000000;\n"
"")
        self.ThroughputFrame_pg2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ThroughputFrame_pg2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ThroughputFrame_pg2.setObjectName("ThroughputFrame_pg2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.ThroughputFrame_pg2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 201, 150))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.ThroughputLayout_pg2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.ThroughputLayout_pg2.setContentsMargins(10, 10, 10, 10)
        self.ThroughputLayout_pg2.setSpacing(10)
        self.ThroughputLayout_pg2.setObjectName("ThroughputLayout_pg2")
        self.TimeLabel_pg2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.TimeLabel_pg2.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.TimeLabel_pg2.setFont(font)
        self.TimeLabel_pg2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TimeLabel_pg2.setObjectName("TimeLabel_pg2")
        self.ThroughputLayout_pg2.addWidget(self.TimeLabel_pg2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.ThroughputDisplay_pg2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.ThroughputDisplay_pg2.setMinimumSize(QtCore.QSize(150, 40))
        self.ThroughputDisplay_pg2.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ThroughputDisplay_pg2.setFont(font)
        self.ThroughputDisplay_pg2.setStyleSheet("border: 2px;\n"
"border-color: rgb(0, 0, 0);\n"
"font: 18pt \"Arial\";\n"
"background-color: rgb(43, 120, 228);\n"
"color: rgb(255, 255, 255);")
        self.ThroughputDisplay_pg2.setLineWidth(4)
        self.ThroughputDisplay_pg2.setMidLineWidth(4)
        self.ThroughputDisplay_pg2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ThroughputDisplay_pg2.setObjectName("ThroughputDisplay_pg2")
        self.ThroughputLayout_pg2.addWidget(self.ThroughputDisplay_pg2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ThroughputLabel_pg2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.ThroughputLabel_pg2.setMaximumSize(QtCore.QSize(100, 40))
        self.ThroughputLabel_pg2.setStyleSheet("font: 14pt \"Arial\";\n"
"border: 0px;")
        self.ThroughputLabel_pg2.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.ThroughputLabel_pg2.setObjectName("ThroughputLabel_pg2")
        self.ThroughputLayout_pg2.addWidget(self.ThroughputLabel_pg2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.InfoLayout_pg2.addWidget(self.ThroughputFrame_pg2, 1, 2, 1, 1)
        self.MaintenanceFrame = QtWidgets.QFrame(parent=self.gridLayoutWidget_5)
        self.MaintenanceFrame.setMinimumSize(QtCore.QSize(300, 170))
        self.MaintenanceFrame.setMaximumSize(QtCore.QSize(350, 180))
        self.MaintenanceFrame.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border: 2px solid #000000;")
        
        self.upload_layout_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget_5)
        self.upload_layout_button.setMinimumSize(QtCore.QSize(130, 30))
        self.upload_layout_button.setStyleSheet("background-color: rgb(40, 15, 100); border: 1px solid #000000; font: 18pt 'Arial';")
        self.upload_layout_button.setObjectName("upload_layout_button")
        self.upload_layout_button.clicked.connect(self.upload_layout)
        self.InfoLayout_pg2.addWidget(self.upload_layout_button, 2, 2, 1, 1)


        self.MaintenanceFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.MaintenanceFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.MaintenanceFrame.setObjectName("MaintenanceFrame")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(parent=self.MaintenanceFrame)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 331, 161))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.MaintenanceLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.MaintenanceLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.MaintenanceLayout.setContentsMargins(0, 0, 0, 10)
        self.MaintenanceLayout.setSpacing(0)
        self.MaintenanceLayout.setObjectName("MaintenanceLayout")
        self.MaintenanceTitle = QtWidgets.QLabel(parent=self.verticalLayoutWidget_5)
        self.MaintenanceTitle.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.MaintenanceTitle.setFont(font)
        self.MaintenanceTitle.setStyleSheet("border: 0px\n"
"")
        self.MaintenanceTitle.setObjectName("MaintenanceTitle")
        self.MaintenanceLayout.addWidget(self.MaintenanceTitle, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.departureLabel_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_5)
        self.departureLabel_2.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.departureLabel_2.setFont(font)
        self.departureLabel_2.setStyleSheet("font: 30pt \"Arial\";\n"
"border: 0px;")
        self.departureLabel_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.departureLabel_2.setLineWidth(2)
        self.departureLabel_2.setObjectName("departureLabel_2")
        self.MaintenanceLayout.addWidget(self.departureLabel_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.MaintenanceButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_5)
        self.MaintenanceButton.setMinimumSize(QtCore.QSize(0, 30))
        self.MaintenanceButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.MaintenanceButton.clicked.connect(self.maintenance_mode)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.MaintenanceButton.setFont(font)
        self.MaintenanceButton.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"border: 1px solid;\n"
"")
        self.MaintenanceButton.setObjectName("MaintenanceButton")
        self.MaintenanceLayout.addWidget(self.MaintenanceButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.InfoLayout_pg2.addWidget(self.MaintenanceFrame, 1, 0, 1, 2)
        self.HeaderFrame_pg2 = QtWidgets.QFrame(parent=self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HeaderFrame_pg2.sizePolicy().hasHeightForWidth())
        self.HeaderFrame_pg2.setSizePolicy(sizePolicy)
        self.HeaderFrame_pg2.setMinimumSize(QtCore.QSize(600, 0))
        self.HeaderFrame_pg2.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.HeaderFrame_pg2.setFont(font)
        self.HeaderFrame_pg2.setStyleSheet("background-color: rgb(75, 120, 228);")
        self.HeaderFrame_pg2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.HeaderFrame_pg2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.HeaderFrame_pg2.setObjectName("HeaderFrame_pg2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(parent=self.HeaderFrame_pg2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, -5, 791, 71))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.HeaderLayout_pg2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.HeaderLayout_pg2.setContentsMargins(0, 0, 0, 0)
        self.HeaderLayout_pg2.setObjectName("HeaderLayout_pg2")
        self.HeaderLabel_pg2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HeaderLabel_pg2.sizePolicy().hasHeightForWidth())
        self.HeaderLabel_pg2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.HeaderLabel_pg2.setFont(font)
        self.HeaderLabel_pg2.setStyleSheet("color: rgb(255, 255, 255);")
        self.HeaderLabel_pg2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.HeaderLabel_pg2.setObjectName("HeaderLabel_pg2")
        self.HeaderLayout_pg2.addWidget(self.HeaderLabel_pg2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.InfoLayout_pg2.addWidget(self.HeaderFrame_pg2, 0, 0, 1, 3)
        self.SearchFrame = QtWidgets.QFrame(parent=self.gridLayoutWidget_5)
        self.SearchFrame.setMinimumSize(QtCore.QSize(200, 0))
        self.SearchFrame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SearchFrame.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border: 2px solid #000000;")
        self.SearchFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.SearchFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.SearchFrame.setLineWidth(2)
        self.SearchFrame.setObjectName("SearchFrame")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(parent=self.SearchFrame)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(-1, -1, 201, 181))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.SearchLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.SearchLayout.setContentsMargins(0, 0, 0, 10)
        self.SearchLayout.setSpacing(5)
        self.SearchLayout.setObjectName("SearchLayout")
        self.SearchLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_6)
        self.SearchLabel.setMaximumSize(QtCore.QSize(200, 40))
        self.SearchLabel.setStyleSheet("font: 24pt \"Arial\";\n"
"border: 0px;\n"
"")
        self.SearchLabel.setObjectName("SearchLabel")
        self.SearchLayout.addWidget(self.SearchLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.BlockSearchSubLayout = QtWidgets.QGridLayout()
        self.BlockSearchSubLayout.setObjectName("BlockSearchSubLayout")
        self.LineSelectorComboBox = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_6)
        self.LineSelectorComboBox.setMinimumSize(QtCore.QSize(90, 0))
        self.LineSelectorComboBox.setMaximumSize(QtCore.QSize(100, 40))
        self.LineSelectorComboBox.setStyleSheet("font: 18pt \"Arial\";")
        self.LineSelectorComboBox.setObjectName("LineSelectorComboBox")
        self.LineSelectorComboBox.addItem("")
        self.LineSelectorComboBox.addItem("")
        self.LineSelectorComboBox.addItem("")
        self.BlockSearchSubLayout.addWidget(self.LineSelectorComboBox, 0, 1, 1, 1)
        self.SearchLineLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_6)
        self.SearchLineLabel.setMaximumSize(QtCore.QSize(70, 40))
        self.SearchLineLabel.setStyleSheet("font: 24pt \"Arial\";\n"
"border: 0px;\n"
"")
        self.SearchLineLabel.setObjectName("SearchLineLabel")
        self.BlockSearchSubLayout.addWidget(self.SearchLineLabel, 0, 0, 1, 1)
        self.BlockSelectorLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_6)
        self.BlockSelectorLabel.setMaximumSize(QtCore.QSize(70, 40))
        self.BlockSelectorLabel.setStyleSheet("font: 24pt \"Arial\";\n"
"border: 0px;")
        self.BlockSelectorLabel.setObjectName("BlockSelectorLabel")
        self.BlockSearchSubLayout.addWidget(self.BlockSelectorLabel, 1, 0, 1, 1)
        self.BlockSelctorWheel = QtWidgets.QSpinBox(parent=self.verticalLayoutWidget_6)
        self.BlockSelctorWheel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.BlockSelctorWheel.setStyleSheet("font: 13pt \"Arial\";")
        self.BlockSelctorWheel.setObjectName("BlockSelctorWheel")
        self.BlockSearchSubLayout.addWidget(self.BlockSelctorWheel, 1, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.SearchLayout.addLayout(self.BlockSearchSubLayout)
        self.SelectBlockButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_6)
        self.SelectBlockButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.SelectBlockButton.setStyleSheet("font: 18pt \"Arial\";\n"
"background-color: rgb(0, 209, 41);\n"
"border: 1px solid;")
        self.SelectBlockButton.setObjectName("SelectBlockButton")
        self.SelectBlockButton.clicked.connect(self.select_block)
        self.SearchLayout.addWidget(self.SelectBlockButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.InfoLayout_pg2.addWidget(self.SearchFrame, 1, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.BlockTable = QtWidgets.QTabWidget(parent=self.gridLayoutWidget_5)
        self.BlockTable.setMinimumSize(QtCore.QSize(775, 200))
        self.BlockTable.setMaximumSize(QtCore.QSize(800, 400))
        self.BlockTable.setStyleSheet("")
        self.BlockTable.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.BlockTable.setUsesScrollButtons(False)
        self.BlockTable.setTabsClosable(False)
        self.BlockTable.setTabBarAutoHide(True)
        self.BlockTable.setObjectName("BlockTable")
        self.BlueLineBlockTab = QtWidgets.QWidget()
        self.BlueLineBlockTab.setObjectName("BlueLineBlockTab")
        self.gridLayoutWidget_12 = QtWidgets.QWidget(parent=self.BlueLineBlockTab)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(0, 0, 781, 371))
        self.gridLayoutWidget_12.setObjectName("gridLayoutWidget_12")
        self.BlueBlockLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_12)
        self.BlueBlockLayout.setContentsMargins(0, 0, 0, 0)
        self.BlueBlockLayout.setObjectName("BlueBlockLayout")
        self.BlueBlockTable = QtWidgets.QTableWidget(parent=self.gridLayoutWidget_12)
        self.BlueBlockTable.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BlueBlockTable.sizePolicy().hasHeightForWidth())
        self.BlueBlockTable.setSizePolicy(sizePolicy)
        self.BlueBlockTable.setStyleSheet("font: 13pt \"Arial\";")
        self.BlueBlockTable.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.BlueBlockTable.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.BlueBlockTable.setLineWidth(2)
        self.BlueBlockTable.setMidLineWidth(0)
        self.BlueBlockTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.BlueBlockTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.BlueBlockTable.setAutoScroll(True)
        self.BlueBlockTable.setShowGrid(True)
        self.BlueBlockTable.setRowCount(0)
        self.BlueBlockTable.setObjectName("BlueBlockTable")
        self.BlueBlockTable.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.BlueBlockTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueBlockTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueBlockTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueBlockTable.setHorizontalHeaderItem(3, item)
        self.BlueBlockTable.horizontalHeader().setCascadingSectionResizes(True)
        self.BlueBlockTable.horizontalHeader().setDefaultSectionSize(130)
        self.BlueBlockTable.horizontalHeader().setHighlightSections(True)
        self.BlueBlockTable.horizontalHeader().setMinimumSectionSize(22)
        self.BlueBlockTable.horizontalHeader().setSortIndicatorShown(False)
        self.BlueBlockTable.horizontalHeader().setStretchLastSection(False)
        self.BlueBlockTable.verticalHeader().setVisible(False)
        self.BlueBlockLayout.addWidget(self.BlueBlockTable, 1, 0, 1, 1)
        self.BlockTable.addTab(self.BlueLineBlockTab, "")
        self.RedLineBlockTab = QtWidgets.QWidget()
        self.RedLineBlockTab.setObjectName("RedLineBlockTab")
        self.gridLayoutWidget_10 = QtWidgets.QWidget(parent=self.RedLineBlockTab)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(0, 0, 791, 371))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.RedBlockLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.RedBlockLayout.setContentsMargins(0, 0, 0, 0)
        self.RedBlockLayout.setObjectName("RedBlockLayout")
        self.RedBlockTable = QtWidgets.QTableWidget(parent=self.gridLayoutWidget_10)
        self.RedBlockTable.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RedBlockTable.sizePolicy().hasHeightForWidth())
        self.RedBlockTable.setSizePolicy(sizePolicy)
        self.RedBlockTable.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.RedBlockTable.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.RedBlockTable.setLineWidth(2)
        self.RedBlockTable.setMidLineWidth(0)
        self.RedBlockTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.RedBlockTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.RedBlockTable.setShowGrid(True)
        self.RedBlockTable.setRowCount(0)
        self.RedBlockTable.setObjectName("RedBlockTable")
        self.RedBlockTable.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.RedBlockTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RedBlockTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RedBlockTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RedBlockTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.RedBlockTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.RedBlockTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.RedBlockTable.setHorizontalHeaderItem(6, item)
        self.RedBlockTable.horizontalHeader().setCascadingSectionResizes(True)
        self.RedBlockTable.horizontalHeader().setDefaultSectionSize(150)
        self.RedBlockTable.horizontalHeader().setHighlightSections(True)
        self.RedBlockTable.horizontalHeader().setMinimumSectionSize(22)
        self.RedBlockTable.horizontalHeader().setSortIndicatorShown(False)
        self.RedBlockTable.horizontalHeader().setStretchLastSection(False)
        self.RedBlockTable.verticalHeader().setVisible(False)
        self.RedBlockLayout.addWidget(self.RedBlockTable, 1, 0, 1, 1)
        self.BlockTable.addTab(self.RedLineBlockTab, "")
        self.GreenLineBlockTab = QtWidgets.QWidget()
        self.GreenLineBlockTab.setObjectName("GreenLineBlockTab")
        self.gridLayoutWidget_11 = QtWidgets.QWidget(parent=self.GreenLineBlockTab)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(0, 0, 791, 371))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.GreenBlockLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.GreenBlockLayout.setContentsMargins(0, 0, 0, 0)
        self.GreenBlockLayout.setObjectName("GreenBlockLayout")
        self.GreenBlockTable = QtWidgets.QTableWidget(parent=self.gridLayoutWidget_11)
        self.GreenBlockTable.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GreenBlockTable.sizePolicy().hasHeightForWidth())
        self.GreenBlockTable.setSizePolicy(sizePolicy)
        self.GreenBlockTable.setMaximumSize(QtCore.QSize(900, 16777215))
        self.GreenBlockTable.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.GreenBlockTable.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.GreenBlockTable.setLineWidth(2)
        self.GreenBlockTable.setMidLineWidth(0)
        self.GreenBlockTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.GreenBlockTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.GreenBlockTable.setShowGrid(True)
        self.GreenBlockTable.setRowCount(0)
        self.GreenBlockTable.setObjectName("GreenBlockTable")
        self.GreenBlockTable.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.GreenBlockTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.GreenBlockTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.GreenBlockTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.GreenBlockTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.GreenBlockTable.setHorizontalHeaderItem(4, item)
        self.GreenBlockTable.horizontalHeader().setCascadingSectionResizes(True)
        self.GreenBlockTable.horizontalHeader().setDefaultSectionSize(150)
        self.GreenBlockTable.horizontalHeader().setHighlightSections(True)
        self.GreenBlockTable.horizontalHeader().setMinimumSectionSize(22)
        self.GreenBlockTable.horizontalHeader().setSortIndicatorShown(False)
        self.GreenBlockTable.horizontalHeader().setStretchLastSection(False)
        self.GreenBlockTable.verticalHeader().setVisible(False)
        self.GreenBlockLayout.addWidget(self.GreenBlockTable, 0, 0, 1, 1)
        self.BlockTable.addTab(self.GreenLineBlockTab, "")
        self.InfoLayout_pg2.addWidget(self.BlockTable, 2, 0, 1, 3)
        self.InfoLayout_pg2.setColumnStretch(0, 1)
        self.InfoLayout_pg2.setRowStretch(0, 1)
        self.pagetab.addTab(self.BlockTab, "")
        self.SimulationTab = QtWidgets.QWidget()
        self.SimulationTab.setObjectName("SimulationTab")
        self.SimulationFrame = QtWidgets.QFrame(parent=self.SimulationTab)
        self.SimulationFrame.setGeometry(QtCore.QRect(150, 10, 511, 271))
        self.SimulationFrame.setMaximumSize(QtCore.QSize(16777215, 400))
        self.SimulationFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.SimulationFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.SimulationFrame.setObjectName("SimulationFrame")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(parent=self.SimulationFrame)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, 511, 271))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.verticalLayoutWidget_7)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SimulationSpeedLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_7)
        self.SimulationSpeedLabel.setMaximumSize(QtCore.QSize(16777215, 80))
        self.SimulationSpeedLabel.setStyleSheet("font: 36pt \"Arial\";")
        self.SimulationSpeedLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.SimulationSpeedLabel.setObjectName("SimulationSpeedLabel")
        self.gridLayout_2.addWidget(self.SimulationSpeedLabel, 0, 0, 1, 3)
        self.SimulationTimeLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_7)
        self.SimulationTimeLabel.setMaximumSize(QtCore.QSize(16777215, 80))
        self.SimulationTimeLabel.setStyleSheet("font: 36pt \"Arial\";")
        self.SimulationTimeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.SimulationTimeLabel.setObjectName("SimulationTimeLabel")
        self.gridLayout_2.addWidget(self.SimulationTimeLabel, 2, 0, 1, 3)
        self.SimulationTimeDisplay = QtWidgets.QLabel(parent=self.verticalLayoutWidget_7)
        self.SimulationTimeDisplay.setMaximumSize(QtCore.QSize(16777215, 50))
        self.SimulationTimeDisplay.setStyleSheet("font: 24pt \"Arial\";")
        self.SimulationTimeDisplay.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.SimulationTimeDisplay.setObjectName("SimulationTimeDisplay")
        self.gridLayout_2.addWidget(self.SimulationTimeDisplay, 3, 0, 1, 3)
        self.x50label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_7)
        self.x50label.setStyleSheet("font: 18pt \"Arial\";")
        self.x50label.setObjectName("x50label")
        self.gridLayout_2.addWidget(self.x50label, 1, 2, 1, 1)
        self.x1label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_7)
        self.x1label.setStyleSheet("font: 18pt \"Arial\";")
        self.x1label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.x1label.setObjectName("x1label")
        self.gridLayout_2.addWidget(self.x1label, 1, 0, 1, 1)
        self.SimulationSpeedSlider = QtWidgets.QSlider(parent=self.verticalLayoutWidget_7)
        self.SimulationSpeedSlider.setMinimumSize(QtCore.QSize(350, 0))
        self.SimulationSpeedSlider.setMaximumSize(QtCore.QSize(350, 16777215))
        self.SimulationSpeedSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.SimulationSpeedSlider.setObjectName("SimulationSpeedSlider")
        self.gridLayout_2.addWidget(self.SimulationSpeedSlider, 1, 1, 1, 1)
        self.pagetab.addTab(self.SimulationTab, "")
        self.TestTab = QtWidgets.QWidget()
        self.TestTab.setObjectName("TestTab")
        self.TestBenchFrame = QtWidgets.QFrame(parent=self.TestTab)
        self.TestBenchFrame.setGeometry(QtCore.QRect(0, 0, 821, 711))
        self.TestBenchFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.TestBenchFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.TestBenchFrame.setObjectName("TestBenchFrame")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.TestBenchFrame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 801, 711))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.TestBenchLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.TestBenchLayout.setContentsMargins(5, 5, 5, 5)
        self.TestBenchLayout.setObjectName("TestBenchLayout")
        self.TrainTable_2 = QtWidgets.QTabWidget(parent=self.gridLayoutWidget)
        self.TrainTable_2.setMinimumSize(QtCore.QSize(0, 200))
        self.TrainTable_2.setMaximumSize(QtCore.QSize(800, 400))
        self.TrainTable_2.setStyleSheet("")
        self.TrainTable_2.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.TrainTable_2.setUsesScrollButtons(False)
        self.TrainTable_2.setTabsClosable(False)
        self.TrainTable_2.setTabBarAutoHide(True)
        self.TrainTable_2.setObjectName("TrainTable_2")
        self.BlueLineTrainsTab_2 = QtWidgets.QWidget()
        self.BlueLineTrainsTab_2.setObjectName("BlueLineTrainsTab_2")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(parent=self.BlueLineTrainsTab_2)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(0, 10, 781, 361))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.BlueTrainsLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.BlueTrainsLayout_6.setContentsMargins(0, 0, 0, 0)
        self.BlueTrainsLayout_6.setObjectName("BlueTrainsLayout_6")
        self.BlueTrainsTable_6 = QtWidgets.QTableWidget(parent=self.gridLayoutWidget_9)
        self.BlueTrainsTable_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.BlueTrainsTable_6.sizePolicy().hasHeightForWidth())
        self.BlueTrainsTable_6.setSizePolicy(sizePolicy)
        self.BlueTrainsTable_6.setMinimumSize(QtCore.QSize(0, 100))
        self.BlueTrainsTable_6.setMaximumSize(QtCore.QSize(750, 600))
        self.BlueTrainsTable_6.setStyleSheet("font: 13pt \"Arial\";")
        self.BlueTrainsTable_6.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.BlueTrainsTable_6.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.BlueTrainsTable_6.setLineWidth(2)
        self.BlueTrainsTable_6.setMidLineWidth(0)
        self.BlueTrainsTable_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.BlueTrainsTable_6.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.BlueTrainsTable_6.setShowGrid(True)
        self.BlueTrainsTable_6.setRowCount(0)
        self.BlueTrainsTable_6.setObjectName("BlueTrainsTable_6")
        self.BlueTrainsTable_6.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable_6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable_6.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable_6.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlueTrainsTable_6.setHorizontalHeaderItem(6, item)
        self.BlueTrainsTable_6.horizontalHeader().setCascadingSectionResizes(True)
        self.BlueTrainsTable_6.horizontalHeader().setDefaultSectionSize(143)
        self.BlueTrainsTable_6.horizontalHeader().setHighlightSections(True)
        self.BlueTrainsTable_6.horizontalHeader().setMinimumSectionSize(22)
        self.BlueTrainsTable_6.horizontalHeader().setSortIndicatorShown(False)
        self.BlueTrainsTable_6.horizontalHeader().setStretchLastSection(False)
        self.BlueTrainsTable_6.verticalHeader().setVisible(False)
        self.BlueTrainsLayout_6.addWidget(self.BlueTrainsTable_6, 0, 0, 1, 1)
        self.TrainTable_2.addTab(self.BlueLineTrainsTab_2, "")
        self.red_line_blocks_tab = QtWidgets.QWidget()
        self.red_line_blocks_tab.setObjectName("red_line_blocks_tab")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(parent=self.red_line_blocks_tab)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(0, 10, 781, 361))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.red_block_tab_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.red_block_tab_layout.setContentsMargins(0, 0, 0, 0)
        self.red_block_tab_layout.setObjectName("red_block_tab_layout")
        self.red_block_tab_widget = QtWidgets.QTableWidget(parent=self.gridLayoutWidget_7)
        self.red_block_tab_widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.red_block_tab_widget.sizePolicy().hasHeightForWidth())
        self.red_block_tab_widget.setSizePolicy(sizePolicy)
        self.red_block_tab_widget.setMinimumSize(QtCore.QSize(0, 100))
        self.red_block_tab_widget.setMaximumSize(QtCore.QSize(750, 600))
        self.red_block_tab_widget.setStyleSheet("font: 13pt \"Arial\";")
        self.red_block_tab_widget.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.red_block_tab_widget.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.red_block_tab_widget.setLineWidth(2)
        self.red_block_tab_widget.setMidLineWidth(0)
        self.red_block_tab_widget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.red_block_tab_widget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.red_block_tab_widget.setShowGrid(True)
        self.red_block_tab_widget.setRowCount(0)
        self.red_block_tab_widget.setObjectName("red_block_tab_widget")
        self.red_block_tab_widget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.red_block_tab_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.red_block_tab_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.red_block_tab_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.red_block_tab_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.red_block_tab_widget.setHorizontalHeaderItem(4, item)
        self.red_block_tab_widget.horizontalHeader().setCascadingSectionResizes(True)
        self.red_block_tab_widget.horizontalHeader().setDefaultSectionSize(143)
        self.red_block_tab_widget.horizontalHeader().setHighlightSections(True)
        self.red_block_tab_widget.horizontalHeader().setMinimumSectionSize(22)
        self.red_block_tab_widget.horizontalHeader().setSortIndicatorShown(False)
        self.red_block_tab_widget.horizontalHeader().setStretchLastSection(False)
        self.red_block_tab_widget.verticalHeader().setVisible(False)
        self.red_block_tab_layout.addWidget(self.red_block_tab_widget, 0, 0, 1, 1)
        self.TrainTable_2.addTab(self.red_line_blocks_tab, "")
        self.green_line_blocks_tab = QtWidgets.QWidget()
        self.green_line_blocks_tab.setObjectName("green_line_blocks_tab")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(parent=self.green_line_blocks_tab)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(0, 10, 781, 361))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.green_block_tab_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.green_block_tab_layout.setContentsMargins(0, 0, 0, 0)
        self.green_block_tab_layout.setObjectName("green_block_tab_layout")
        self.green_block_tab_widget = QtWidgets.QTableWidget(parent=self.gridLayoutWidget_8)
        self.green_block_tab_widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.green_block_tab_widget.sizePolicy().hasHeightForWidth())
        self.green_block_tab_widget.setSizePolicy(sizePolicy)
        self.green_block_tab_widget.setMinimumSize(QtCore.QSize(0, 100))
        self.green_block_tab_widget.setMaximumSize(QtCore.QSize(750, 600))
        self.green_block_tab_widget.setStyleSheet("font: 13pt \"Arial\";")
        self.green_block_tab_widget.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.green_block_tab_widget.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.green_block_tab_widget.setLineWidth(2)
        self.green_block_tab_widget.setMidLineWidth(0)
        self.green_block_tab_widget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.green_block_tab_widget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.green_block_tab_widget.setShowGrid(True)
        self.green_block_tab_widget.setRowCount(0)
        self.green_block_tab_widget.setObjectName("green_block_tab_widget")
        self.green_block_tab_widget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.green_block_tab_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.green_block_tab_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.green_block_tab_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.green_block_tab_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.green_block_tab_widget.setHorizontalHeaderItem(4, item)
        self.green_block_tab_widget.horizontalHeader().setCascadingSectionResizes(True)
        self.green_block_tab_widget.horizontalHeader().setDefaultSectionSize(143)
        self.green_block_tab_widget.horizontalHeader().setHighlightSections(True)
        self.green_block_tab_widget.horizontalHeader().setMinimumSectionSize(22)
        self.green_block_tab_widget.horizontalHeader().setSortIndicatorShown(False)
        self.green_block_tab_widget.horizontalHeader().setStretchLastSection(False)
        self.green_block_tab_widget.verticalHeader().setVisible(False)
        self.green_block_tab_layout.addWidget(self.green_block_tab_widget, 0, 0, 1, 1)
        self.TrainTable_2.addTab(self.green_line_blocks_tab, "")
        self.TestBenchLayout.addWidget(self.TrainTable_2, 4, 0, 1, 2)
        self.frame_3 = QtWidgets.QFrame(parent=self.gridLayoutWidget)
        self.frame_3.setStyleSheet("border: 2px solid #000000;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(parent=self.frame_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 791, 102))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.input_output_frame = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.input_output_frame.setContentsMargins(0, 0, 30, 0)
        self.input_output_frame.setObjectName("input_output_frame")
        self.has_signal_checkbox = QtWidgets.QCheckBox(parent=self.gridLayoutWidget_4)
        self.has_signal_checkbox.setStyleSheet("font: 13pt \"Arial\";\n"
"border: 0 px;")
        self.has_signal_checkbox.setObjectName("has_signal_checkbox")
        self.input_output_frame.addWidget(self.has_signal_checkbox, 1, 1, 1, 1)
        self.switch_checkbox = QtWidgets.QCheckBox(parent=self.gridLayoutWidget_4)
        self.switch_checkbox.setStyleSheet("font: 13pt \"Arial\";\n"
"border: 0 px;")
        self.switch_checkbox.setObjectName("switch_checkbox")
        self.input_output_frame.addWidget(self.switch_checkbox, 0, 1, 1, 1)
        self.crossing_checkbox = QtWidgets.QCheckBox(parent=self.gridLayoutWidget_4)
        self.crossing_checkbox.setStyleSheet("font: 13pt \"Arial\";\n"
"border: 0px;")
        self.crossing_checkbox.setObjectName("crossing_checkbox")
        self.input_output_frame.addWidget(self.crossing_checkbox, 2, 0, 1, 1)
        self.track_damaged_checkbox = QtWidgets.QCheckBox(parent=self.gridLayoutWidget_4)
        self.track_damaged_checkbox.setStyleSheet("font: 13pt \"Arial\";\n"
"border: 0px;")
        self.track_damaged_checkbox.setObjectName("track_damaged_checkbox")
        self.input_output_frame.addWidget(self.track_damaged_checkbox, 1, 0, 1, 1)
        self.has_crossing_checkbox = QtWidgets.QCheckBox(parent=self.gridLayoutWidget_4)
        self.has_crossing_checkbox.setStyleSheet("font: 13pt \"Arial\";\n"
"border: 0 px;")
        self.has_crossing_checkbox.setObjectName("has_crossing_checkbox")
        self.input_output_frame.addWidget(self.has_crossing_checkbox, 2, 1, 1, 1)
        self.block_occupied_checkbox = QtWidgets.QCheckBox(parent=self.gridLayoutWidget_4)
        self.block_occupied_checkbox.setStyleSheet("border: 0px;\n"
"font: 13pt \"Arial\";")
        self.block_occupied_checkbox.setObjectName("block_occupied_checkbox")
        self.input_output_frame.addWidget(self.block_occupied_checkbox, 0, 0, 1, 1)
        self.combo_box_frame = QtWidgets.QFrame(parent=self.gridLayoutWidget_4)
        self.combo_box_frame.setStyleSheet("border: 0px\n"
"")
        self.combo_box_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.combo_box_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.combo_box_frame.setObjectName("combo_box_frame")
        self.gridLayoutWidget_13 = QtWidgets.QWidget(parent=self.combo_box_frame)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(0, 0, 241, 81))
        self.gridLayoutWidget_13.setObjectName("gridLayoutWidget_13")
        self.combo_box_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_13)
        self.combo_box_layout.setContentsMargins(0, 0, 0, 0)
        self.combo_box_layout.setObjectName("combo_box_layout")
        self.switch_selector = QtWidgets.QComboBox(parent=self.gridLayoutWidget_13)
        self.switch_selector.setStyleSheet("font: 13pt \"Arial\";")
        self.switch_selector.setObjectName("switch_selector")
        self.combo_box_layout.addWidget(self.switch_selector, 1, 0, 1, 1)
        self.switch_direction_label = QtWidgets.QLabel(parent=self.gridLayoutWidget_13)
        self.switch_direction_label.setStyleSheet("font: 13pt \"Arial\";")
        self.switch_direction_label.setObjectName("switch_direction_label")
        self.combo_box_layout.addWidget(self.switch_direction_label, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.signal_state_label = QtWidgets.QLabel(parent=self.gridLayoutWidget_13)
        self.signal_state_label.setStyleSheet("font: 13pt \"Arial\";")
        self.signal_state_label.setObjectName("signal_state_label")
        self.combo_box_layout.addWidget(self.signal_state_label, 0, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.signal_selector = QtWidgets.QComboBox(parent=self.gridLayoutWidget_13)
        self.signal_selector.setStyleSheet("font: 13pt \"Arial\";")
        self.signal_selector.setObjectName("signal_selector")
        self.combo_box_layout.addWidget(self.signal_selector, 1, 1, 1, 1)
        self.input_output_frame.addWidget(self.combo_box_frame, 0, 2, 3, 1)
        self.TestBenchLayout.addWidget(self.frame_3, 3, 0, 1, 2)
        self.HeaderFrame_pg3 = QtWidgets.QFrame(parent=self.gridLayoutWidget)
        self.HeaderFrame_pg3.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.HeaderFrame_pg3.setFont(font)
        self.HeaderFrame_pg3.setStyleSheet("background-color: rgb(75, 120, 228);")
        self.HeaderFrame_pg3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.HeaderFrame_pg3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.HeaderFrame_pg3.setObjectName("HeaderFrame_pg3")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(parent=self.HeaderFrame_pg3)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(-1, -1, 801, 61))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.HeaderLayout_pg3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.HeaderLayout_pg3.setContentsMargins(0, 0, 0, 0)
        self.HeaderLayout_pg3.setObjectName("HeaderLayout_pg3")
        self.HeaderLabel_pg3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.HeaderLabel_pg3.setFont(font)
        self.HeaderLabel_pg3.setStyleSheet("color: rgb(255, 255, 255);")
        self.HeaderLabel_pg3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.HeaderLabel_pg3.setObjectName("HeaderLabel_pg3")
        self.HeaderLayout_pg3.addWidget(self.HeaderLabel_pg3)
        self.TestBenchLayout.addWidget(self.HeaderFrame_pg3, 0, 0, 1, 2)
        self.train_outputs_frame = QtWidgets.QFrame(parent=self.gridLayoutWidget)
        self.train_outputs_frame.setStyleSheet("border: 2px solid #000000")
        self.train_outputs_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.train_outputs_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.train_outputs_frame.setLineWidth(2)
        self.train_outputs_frame.setObjectName("train_outputs_frame")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(parent=self.train_outputs_frame)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(-1, -1, 531, 101))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.train_outputs_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.train_outputs_layout.setContentsMargins(10, 10, 10, 10)
        self.train_outputs_layout.setObjectName("train_outputs_layout")
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget_6)
        self.label_2.setStyleSheet("border: 0px;\n"
"font: 18pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.train_outputs_layout.addWidget(self.label_2, 1, 2, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.suggested_speed_display = QtWidgets.QLabel(parent=self.gridLayoutWidget_6)
        self.suggested_speed_display.setStyleSheet("border: 2px solid #000000;\n"
"font: 13pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);")
        self.suggested_speed_display.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.suggested_speed_display.setObjectName("suggested_speed_display")
        self.train_outputs_layout.addWidget(self.suggested_speed_display, 1, 1, 1, 1)
        self.train_number_selector = QtWidgets.QSpinBox(parent=self.gridLayoutWidget_6)
        self.train_number_selector.setStyleSheet("font: 13pt \"Arial\";")
        self.train_number_selector.setObjectName("train_number_selector")
        self.train_outputs_layout.addWidget(self.train_number_selector, 0, 1, 1, 1)
        self.train_number_label = QtWidgets.QLabel(parent=self.gridLayoutWidget_6)
        self.train_number_label.setStyleSheet("font: 18pt \"Arial\";\n"
"border: 0px;")
        self.train_number_label.setObjectName("train_number_label")
        self.train_outputs_layout.addWidget(self.train_number_label, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 0px;\n"
"font: 18pt \"Arial\";")
        self.label.setObjectName("label")
        self.train_outputs_layout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget_6)
        self.label_3.setStyleSheet("border: 2px solid #000000;\n"
"font: 13pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.train_outputs_layout.addWidget(self.label_3, 1, 3, 1, 1)
        self.train_outputs_label = QtWidgets.QLabel(parent=self.gridLayoutWidget_6)
        self.train_outputs_label.setMinimumSize(QtCore.QSize(200, 50))
        self.train_outputs_label.setStyleSheet("font: 24pt \"Arial\";\n"
"border: 0px;")
        self.train_outputs_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.train_outputs_label.setObjectName("train_outputs_label")
        self.train_outputs_layout.addWidget(self.train_outputs_label, 0, 2, 1, 2)
        self.TestBenchLayout.addWidget(self.train_outputs_frame, 1, 1, 1, 1)
        self.BlockSelectorFrame = QtWidgets.QFrame(parent=self.gridLayoutWidget)
        self.BlockSelectorFrame.setMaximumSize(QtCore.QSize(250, 150))
        self.BlockSelectorFrame.setStyleSheet("border: 2px solid #000000;")
        self.BlockSelectorFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BlockSelectorFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BlockSelectorFrame.setLineWidth(2)
        self.BlockSelectorFrame.setObjectName("BlockSelectorFrame")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(parent=self.BlockSelectorFrame)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(-1, -11, 251, 140))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.BlockSelectorLayout = QtWidgets.QGridLayout(self.verticalLayoutWidget_9)
        self.BlockSelectorLayout.setContentsMargins(10, 20, 10, 20)
        self.BlockSelectorLayout.setObjectName("BlockSelectorLayout")
        self.TestBenchBlockSelector = QtWidgets.QSpinBox(parent=self.verticalLayoutWidget_9)
        self.TestBenchBlockSelector.setMaximumSize(QtCore.QSize(16777215, 30))
        self.TestBenchBlockSelector.setStyleSheet("font: 13pt \"Arial\";")
        self.TestBenchBlockSelector.setObjectName("TestBenchBlockSelector")
        self.BlockSelectorLayout.addWidget(self.TestBenchBlockSelector, 2, 1, 3, 2)
        self.TestBenchBlockLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_9)
        self.TestBenchBlockLabel.setMinimumSize(QtCore.QSize(0, 50))
        self.TestBenchBlockLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.TestBenchBlockLabel.setStyleSheet("font: 18pt \"Arial\";\n"
"border: 0px;")
        self.TestBenchBlockLabel.setObjectName("TestBenchBlockLabel")
        self.BlockSelectorLayout.addWidget(self.TestBenchBlockLabel, 2, 0, 3, 1, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.TestBenchLineLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_9)
        self.TestBenchLineLabel.setMinimumSize(QtCore.QSize(0, 40))
        self.TestBenchLineLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.TestBenchLineLabel.setStyleSheet("font: 18pt \"Arial\";\n"
"border: 0px;")
        self.TestBenchLineLabel.setObjectName("TestBenchLineLabel")
        self.BlockSelectorLayout.addWidget(self.TestBenchLineLabel, 0, 0, 2, 1, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.TestBenchLineSelector = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_9)
        self.TestBenchLineSelector.setMinimumSize(QtCore.QSize(0, 30))
        self.TestBenchLineSelector.setMaximumSize(QtCore.QSize(16777215, 30))
        self.TestBenchLineSelector.setStyleSheet("font: 13pt \"Arial\";")
        self.TestBenchLineSelector.setObjectName("TestBenchLineSelector")
        self.TestBenchLineSelector.addItem("")
        self.TestBenchLineSelector.addItem("")
        self.TestBenchLineSelector.addItem("")
        self.BlockSelectorLayout.addWidget(self.TestBenchLineSelector, 0, 1, 2, 2, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.TestBenchLayout.addWidget(self.BlockSelectorFrame, 1, 0, 1, 1)
        self.pagetab.addTab(self.TestTab, "")
        self.gridLayout.addWidget(self.pagetab, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        mainwindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainwindow)
        self.pagetab.setCurrentIndex(0)
        self.TrainTable.setCurrentIndex(0)
        self.train_vew_line_selector.setCurrentIndex(2)
        self.LineSelectorComboBox.setCurrentIndex(2)
        self.BlockTable.setCurrentIndex(0)
        self.TrainTable_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "MainWindow"))
        self.TimeLabel.setText(_translate("mainwindow", "10:30"))
        self.ThroughputDisplay.setText(_translate("mainwindow", "X Trains/hr/line"))
        self.ThroughputLabel.setText(_translate("mainwindow", "Throughput"))
        self.UploadScheduleButton.setText(_translate("mainwindow", "Upload Schedule"))
        item = self.BlueTrainsTable.horizontalHeaderItem(0)
        item.setText(_translate("mainwindow", "Train #"))
        item = self.BlueTrainsTable.horizontalHeaderItem(1)
        item.setText(_translate("mainwindow", "Current Block"))
        item = self.BlueTrainsTable.horizontalHeaderItem(2)
        item.setText(_translate("mainwindow", "Next Destination"))
        item = self.BlueTrainsTable.horizontalHeaderItem(3)
        item.setText(_translate("mainwindow", "Arrival Time"))
        item = self.BlueTrainsTable.horizontalHeaderItem(4)
        item.setText(_translate("mainwindow", "Yard Departure Time"))
        self.TrainTable.setTabText(self.TrainTable.indexOf(self.BlueLineTrainsTab), _translate("mainwindow", "Blue Line"))
        item = self.BlueTrainsTable_2.horizontalHeaderItem(0)
        item.setText(_translate("mainwindow", "Train #"))
        item = self.BlueTrainsTable_2.horizontalHeaderItem(1)
        item.setText(_translate("mainwindow", "Current Block"))
        item = self.BlueTrainsTable_2.horizontalHeaderItem(2)
        item.setText(_translate("mainwindow", "Destination"))
        item = self.BlueTrainsTable_2.horizontalHeaderItem(3)
        item.setText(_translate("mainwindow", "DepartureTime"))
        item = self.BlueTrainsTable_2.horizontalHeaderItem(4)
        item.setText(_translate("mainwindow", "Arrival Time"))
        self.TrainTable.setTabText(self.TrainTable.indexOf(self.RedLineTrainsTab), _translate("mainwindow", "Red Line"))
        self.TrainTable.setTabText(self.TrainTable.indexOf(self.GreenLineTrainsTab), _translate("mainwindow", "Green Line"))
        self.automatic_manual_toggle.setText(_translate("mainwindow", "Manual Mode"))
        self.ScheduleTitle.setText(_translate("mainwindow", "Schedule New Train"))
        self.destinationLabel.setText(_translate("mainwindow", "Destination Station:"))
        self.departureLabel.setText(_translate("mainwindow", "Departure Time:"))
        self.ArrivalLabel.setText(_translate("mainwindow", "Arrival Time:"))
        self.DispatchButton.setText(_translate("mainwindow", "Dispatch Train"))
        self.LineLabel.setText(_translate("mainwindow", "Line:"))
        self.train_vew_line_selector.setItemText(0, _translate("mainwindow", "Blue"))
        self.train_vew_line_selector.setItemText(1, _translate("mainwindow", "Red"))
        self.train_vew_line_selector.setItemText(2, _translate("mainwindow", "Green"))
        self.add_destination_button.setText(_translate("mainwindow", "Add Destination"))
        self.destination_list_label.setText(_translate("mainwindow", "Destinations:"))
        self.HeaderLabel.setText(_translate("mainwindow", "CTC"))
        self.pagetab.setTabText(self.pagetab.indexOf(self.TrainTab), _translate("mainwindow", "Train View"))
        self.pagetab.setTabToolTip(self.pagetab.indexOf(self.TrainTab), _translate("mainwindow", "Schedule new trains & view existing train information"))
        self.TimeLabel_pg2.setText(_translate("mainwindow", "10:30"))
        self.ThroughputDisplay_pg2.setText(_translate("mainwindow", "X Trains/hr/line"))
        self.ThroughputLabel_pg2.setText(_translate("mainwindow", "Throughput"))
        self.upload_layout_button.setText(_translate("mainwindow", "Upload Layout"))
        self.MaintenanceTitle.setText(_translate("mainwindow", "Place Block in Maintanence Mode"))
        self.departureLabel_2.setText(_translate("mainwindow", "Blue Line - Block #2"))
        self.MaintenanceButton.setText(_translate("mainwindow", "Maintenance Mode"))
        self.HeaderLabel_pg2.setText(_translate("mainwindow", "CTC"))
        self.SearchLabel.setText(_translate("mainwindow", "Search Blocks"))
        self.LineSelectorComboBox.setItemText(0, _translate("mainwindow", "Blue"))
        self.LineSelectorComboBox.setItemText(1, _translate("mainwindow", "Red"))
        self.LineSelectorComboBox.setItemText(2, _translate("mainwindow", "Green"))
        self.SearchLineLabel.setText(_translate("mainwindow", "Line:"))
        self.BlockSelectorLabel.setText(_translate("mainwindow", "Block:"))
        self.SelectBlockButton.setText(_translate("mainwindow", "Select Block"))
        item = self.BlueBlockTable.horizontalHeaderItem(0)
        item.setText(_translate("mainwindow", "Block #"))
        item = self.BlueBlockTable.horizontalHeaderItem(1)
        item.setText(_translate("mainwindow", "Section ID"))
        item = self.BlueBlockTable.horizontalHeaderItem(2)
        item.setText(_translate("mainwindow", "Occupied"))
        item = self.BlueBlockTable.horizontalHeaderItem(3)
        item.setText(_translate("mainwindow", "Maintenance"))
        self.BlockTable.setTabText(self.BlockTable.indexOf(self.BlueLineBlockTab), _translate("mainwindow", "Blue Line"))
        item = self.RedBlockTable.horizontalHeaderItem(0)
        item.setText(_translate("mainwindow", "Block #"))
        item = self.RedBlockTable.horizontalHeaderItem(1)
        item.setText(_translate("mainwindow", "Section ID"))
        item = self.RedBlockTable.horizontalHeaderItem(2)
        item.setText(_translate("mainwindow", "Occupied"))
        item = self.RedBlockTable.horizontalHeaderItem(3)
        item.setText(_translate("mainwindow", "Track Damage"))
        item = self.RedBlockTable.horizontalHeaderItem(4)
        item.setText(_translate("mainwindow", "Signal State"))
        item = self.RedBlockTable.horizontalHeaderItem(5)
        item.setText(_translate("mainwindow", "Switch State"))
        item = self.RedBlockTable.horizontalHeaderItem(6)
        item.setText(_translate("mainwindow", "Crossing"))
        self.BlockTable.setTabText(self.BlockTable.indexOf(self.RedLineBlockTab), _translate("mainwindow", "Red Line"))
        item = self.GreenBlockTable.horizontalHeaderItem(0)
        item.setText(_translate("mainwindow", "Train #"))
        item = self.GreenBlockTable.horizontalHeaderItem(1)
        item.setText(_translate("mainwindow", "Current Block"))
        item = self.GreenBlockTable.horizontalHeaderItem(2)
        item.setText(_translate("mainwindow", "Destination"))
        item = self.GreenBlockTable.horizontalHeaderItem(3)
        item.setText(_translate("mainwindow", "DepartureTime"))
        item = self.GreenBlockTable.horizontalHeaderItem(4)
        item.setText(_translate("mainwindow", "Arrival Time"))
        self.BlockTable.setTabText(self.BlockTable.indexOf(self.GreenLineBlockTab), _translate("mainwindow", "Green Line"))
        self.pagetab.setTabText(self.pagetab.indexOf(self.BlockTab), _translate("mainwindow", "Block View"))
        self.pagetab.setTabToolTip(self.pagetab.indexOf(self.BlockTab), _translate("mainwindow", "View the status of blocks"))
        self.SimulationSpeedLabel.setText(_translate("mainwindow", "Simulation Speed"))
        self.SimulationTimeLabel.setText(_translate("mainwindow", "Simulation Time"))
        self.SimulationTimeDisplay.setText(_translate("mainwindow", "00:00:00"))
        self.x50label.setText(_translate("mainwindow", "50x"))
        self.x1label.setText(_translate("mainwindow", "1x"))
        self.pagetab.setTabText(self.pagetab.indexOf(self.SimulationTab), _translate("mainwindow", "Simulation"))
        self.pagetab.setTabToolTip(self.pagetab.indexOf(self.SimulationTab), _translate("mainwindow", "View and modify the simulation parameters"))
        item = self.BlueTrainsTable_6.horizontalHeaderItem(0)
        item.setText(_translate("mainwindow", "Block #"))
        item = self.BlueTrainsTable_6.horizontalHeaderItem(1)
        item.setText(_translate("mainwindow", "Section ID"))
        item = self.BlueTrainsTable_6.horizontalHeaderItem(2)
        item.setText(_translate("mainwindow", "Occupied"))
        item = self.BlueTrainsTable_6.horizontalHeaderItem(3)
        item.setText(_translate("mainwindow", "Track Damage"))
        item = self.BlueTrainsTable_6.horizontalHeaderItem(4)
        item.setText(_translate("mainwindow", "Signal State"))
        item = self.BlueTrainsTable_6.horizontalHeaderItem(5)
        item.setText(_translate("mainwindow", "Switch State"))
        item = self.BlueTrainsTable_6.horizontalHeaderItem(6)
        item.setText(_translate("mainwindow", "Crossing"))
        self.TrainTable_2.setTabText(self.TrainTable_2.indexOf(self.BlueLineTrainsTab_2), _translate("mainwindow", "Blue Line"))
        item = self.red_block_tab_widget.horizontalHeaderItem(0)
        item.setText(_translate("mainwindow", "Train #"))
        item = self.red_block_tab_widget.horizontalHeaderItem(1)
        item.setText(_translate("mainwindow", "Current Block"))
        item = self.red_block_tab_widget.horizontalHeaderItem(2)
        item.setText(_translate("mainwindow", "Destination"))
        item = self.red_block_tab_widget.horizontalHeaderItem(3)
        item.setText(_translate("mainwindow", "DepartureTime"))
        item = self.red_block_tab_widget.horizontalHeaderItem(4)
        item.setText(_translate("mainwindow", "Arrival Time"))
        self.TrainTable_2.setTabText(self.TrainTable_2.indexOf(self.red_line_blocks_tab), _translate("mainwindow", "Red Line"))
        item = self.green_block_tab_widget.horizontalHeaderItem(0)
        item.setText(_translate("mainwindow", "Train #"))
        item = self.green_block_tab_widget.horizontalHeaderItem(1)
        item.setText(_translate("mainwindow", "Current Block"))
        item = self.green_block_tab_widget.horizontalHeaderItem(2)
        item.setText(_translate("mainwindow", "Destination"))
        item = self.green_block_tab_widget.horizontalHeaderItem(3)
        item.setText(_translate("mainwindow", "DepartureTime"))
        item = self.green_block_tab_widget.horizontalHeaderItem(4)
        item.setText(_translate("mainwindow", "Arrival Time"))
        self.TrainTable_2.setTabText(self.TrainTable_2.indexOf(self.green_line_blocks_tab), _translate("mainwindow", "Green Line"))
        self.has_signal_checkbox.setText(_translate("mainwindow", "Has signal?"))
        self.switch_checkbox.setText(_translate("mainwindow", "Has switch?"))
        self.crossing_checkbox.setText(_translate("mainwindow", "Crossing Closed"))
        self.track_damaged_checkbox.setText(_translate("mainwindow", "Track Damaged"))
        self.has_crossing_checkbox.setText(_translate("mainwindow", "Has crossing?"))
        self.block_occupied_checkbox.setText(_translate("mainwindow", "Block Occupied"))
        self.switch_direction_label.setText(_translate("mainwindow", "Switch Direction:"))
        self.signal_state_label.setText(_translate("mainwindow", "Signal State:"))
        self.HeaderLabel_pg3.setText(_translate("mainwindow", "CTC"))
        self.label_2.setText(_translate("mainwindow", "Authority:"))
        self.suggested_speed_display.setText(_translate("mainwindow", "20mph"))
        self.train_number_label.setText(_translate("mainwindow", "  Train #:"))
        self.label.setText(_translate("mainwindow", "Suggested Speed:"))
        self.label_3.setText(_translate("mainwindow", "300m"))
        self.train_outputs_label.setText(_translate("mainwindow", "Outputs to Train"))
        self.TestBenchBlockLabel.setText(_translate("mainwindow", "Block:"))
        self.TestBenchLineLabel.setText(_translate("mainwindow", "Line:"))
        self.TestBenchLineSelector.setItemText(0, _translate("mainwindow", "Blue"))
        self.TestBenchLineSelector.setItemText(1, _translate("mainwindow", "Red"))
        self.TestBenchLineSelector.setItemText(2, _translate("mainwindow", "Green"))
        self.pagetab.setTabText(self.pagetab.indexOf(self.TestTab), _translate("mainwindow", "Test Bench"))
        self.pagetab.setTabToolTip(self.pagetab.indexOf(self.TestTab), _translate("mainwindow", "Test I/O operation"))


    def updateUI(self):

        _translate = QtCore.QCoreApplication.translate

        self.TimeLabel.setText(self.wall_clock_time.strftime("%H:%M"))
        #self.ThroughputDisplay.setText(self.ctc.get_throughput())
        #self.ThroughputDisplay_pg2.setText(self.ctc.get_throughput())
        #self.ThroughputDisplay_pg3.setText(self.ctc.get_throughput())
        #self.SimulationTimeDisplay.setText(self.ctc.get_time())
        #self.suggested_speed_display.setText(self.ctc.get_suggested_speed())
        #self.label_3.setText(self.ctc.get_authority())
        #self.label.setText(self.ctc.get_suggested_speed())
        
        self.BlueTrainsTable.clear()
        self.BlueTrainsTable.setRowCount(len(self.ctc.line.train_list))

        for index, train in enumerate(self.ctc.line.train_list):
            self.BlueTrainsTable.setItem(index, 0, QtWidgets.QTableWidgetItem(str(train.train_id)))
            self.BlueTrainsTable.setItem(index, 1, QtWidgets.QTableWidgetItem(str(train.location)))
            self.BlueTrainsTable.setItem(index, 2, QtWidgets.QTableWidgetItem(str(train.destination_station)))
            self.BlueTrainsTable.setItem(index, 3, QtWidgets.QTableWidgetItem(str(train.arrival_time)))
            self.BlueTrainsTable.setItem(index, 4, QtWidgets.QTableWidgetItem(str(train.departure_time)))
        
            for col in range(5):
                item1 = self.BlueTrainsTable.item(index, col)
                item1.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

        self.BlueTrainsTable.setColumnCount(5)

        headers = ["Train #", "Current Block", "Next Destination", "Arrival Time", "Yard Departure Time"]
        for col, header in enumerate(headers):
            item = self.BlueTrainsTable.horizontalHeaderItem(col)
            if item is None:
                item = QtWidgets.QTableWidgetItem()
                self.BlueTrainsTable.setHorizontalHeaderItem(col, item)
            item.setText(_translate("mainwindow", header))

        self.BlueTrainsTable.setShowGrid(True)


    def update_block_occupancies(self, blocks: list):
        # Connected to CTC-Wayside Communication - gets block occupancies from signal

        # Updates Block Occupancies and Updates: Train Locations, Authorities, Speeds, Throughput
        self.ctc.update_blocks_on_line(blocks)

        # Once calculations have been made, update the UI
        self.updateUI()

    def dispatch_train(self):
            

        station = self.StationSelector.currentText()
        print(f"Selected Station = {station}")

        dest = self.ctc.find_destination(station)
        if dest == -1:
            print("Invalid Destination")
            return
        else:
            
            departure_time = self.DepartureSelector.time()
            print(f"Departure Time = {departure_time.toString()}")
            depart_time = dt.time(hour=departure_time.hour(),minute=departure_time.minute(),second=departure_time.second())
            print(depart_time)
            self.ctc.add_new_train_to_line("Green", dest, station, depart_time)
            self.ctc_train_communicate.dispatch_train_signal.emit(1)

        self.updateUI()
        
        
    def add_destination(self):
        pass
    
    def select_block(self):
        pass
    
    def maintenance_mode(self):
        pass
    
    def auto_manual_toggle(self):
        self.ctc.toggle_automatic_manual()
        _translate = QtCore.QCoreApplication.translate
        if self.ctc.automatic:
            self.automatic_manual_toggle.setText(_translate("mainwindow", "Manual Mode"))
        else:
            self.automatic_manual_toggle.setText(_translate("mainwindow", "Auto Mode"))
    
    def upload_schedule(self):
        pass
    
    def upload_layout(self):
        filename, _ = QFileDialog.getOpenFileName(None, "Select Layout File", os.getcwd(), "Excel File (*.xlsx *.xls)")
        if filename:
            print("filename = ", filename)
            self.ctc.upload_layout_to_line(filename)

        # Update Lines Selector
        self.LineSelectorComboBox.clear()
        self.LineSelectorComboBox.addItem("Green")

        # Update Station Selector
        self.StationSelector.clear()
        stations = self.ctc.get_stations()
        print("Stations = ", stations)
        self.StationSelector.addItems(stations)


    def time_step(self):

        date = dt.datetime.now().date()
        datetime = dt.datetime.combine(date, self.wall_clock_time)
        datetime = datetime + dt.timedelta(milliseconds=100)

        self.wall_clock_time = datetime.time()

        self.updateUI()
        

        
    




if __name__ == "__main__":
    
    """"Main"""
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()

    comm = CTCTrain()

    ui = CTC_frontend(comm)
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec())